<?php 
        $upd = [
            "CREATE TABLE Blocks(
                id INT PRIMARY KEY,
                hash VARCHAR (64),
                time TIME,
                median_time TIME,
                size INT,
                stripped_size INT,
                weight INT,
                version INT,
                version_hex VARCHAR(10),
                version_bits VARCHAR (30),
                merkle_root VARCHAR (64),
                nonce BIGINT,
                bits INT,
                difficulty BIGINT,
                chainwork VARCHAR (64),
                coinbase_data_hex VARCHAR (200),
                transaction_count INT,
                witness_count INT,
                input_count INT,
                output_count INT,
                input_total BIGINT,
                input_total_usd DECIMAL,
                output_total BIGINT,
                output_total_usd DECIMAL,
                fee_total INT,
                fee_total_usd DECIMAL,
                fee_per_kb DECIMAL,
                fee_per_kb_usd DECIMAL,
                fee_per_kwu DECIMAL,
                fee_per_kwu_usd DECIMAL,
                cdd_total DECIMAL,
                generation INT,
                generation_usd DECIMAL,
                reward INT,
                reward_usd DECIMAL,
                guessed_miner VARCHAR (64)
            )",
            "CREATE TABLE Inputs (
                block_id INT,
                transaction_hash VARCHAR (64),
                index INT,
                time TIME,
                value BIGINT,
                value_usd DECIMAL,
                recipient VARCHAR (200),
                type VARCHAR (128),
                script_hex VARCHAR (200),
                is_from_coinbase INT,
                is_spendable INT,
                spending_block_id BIGINT,
                spending_transaction_hash VARCHAR (64),
                spending_index INT,
                spending_time TIME,
                spending_value_usd DECIMAL,
                spending_sequence BIGINT,
                spending_signature_hex VARCHAR (300),
                spending_witness VARCHAR (64),
                lifespan BIGINT,
                cdd DECIMAL
            )",
            "CREATE TABLE Outputs (
                block_id INT,
                transaction_hash VARCHAR (64),
                index INT,
                time TIME,
                value BIGINT,
                value_usd DECIMAL,
                recipient VARCHAR (200),
                type VARCHAR (128),
                script_hex VARCHAR (200),
                is_from_coinbase INT,
                is_spendable INT,
                
            )"
        ];
?>
